#!/bin/bash

function f5() {
  CURRENT_DIR=$(pwd)

  case "$(uname)" in
    Linux)
      sudo apt update -y
      sudo apt dist-upgrade -y
      sudo apt autoremove -y
      sudo apt clean all -y

      ;;
    Darwin)
      brew update
      brew cleanup
      brew upgrade
      brew cu --all --yes --cleanup
      brew cleanup
      brew prune
      brew cleanup
      mas upgrade
      sudo softwareupdate -i -a

      ;;
  esac

  # Dotfiles
  cd ~/.dotfiles || exit 1
  git pull-sub
  git submodule update --recursive --remote

  # Npm packages
  sudo yarn global upgrade

  # Vim plugins
  vim +PlugUpgrade +PlugUpdate +qall
  rm ~/.vim/autoload/plug.vim.old > /dev/null 2>&1

  # Tmux plugins
  cd ~/.tmux/plugins/tmux-battery && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-copycat && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-prefix-highlight && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-yank && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-better-mouse-mode && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-cpu && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-resurrect && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-continuum && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-pain-control && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-sensible && git checkout master && git pull

  # Oh-my-zsh
  cd ~/.oh-my-zsh && git checkout master && git pull
  source ~/.zshrc

  cd $CURRENT_DIR
}
