#!/bin/bash

function f5() {
  # Ask for the administrator password upfront
  sudo -v

  # Keep-alive: update existing `sudo` time stamp
  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

  CURRENT_DIR=$(pwd)

  case "$(uname)" in
    Linux)
      sudo apt update -y
      sudo apt dist-upgrade -y
      sudo apt autoremove -y
      sudo apt clean all -y

      ;;
    Darwin)
      brew update
      brew upgrade
      brew cu --all --yes --cleanup
      brew prune
      brew cleanup
      mas upgrade
      sudo softwareupdate -i -a

      ;;
  esac

  # Dotfiles
  cd ~/.dotfiles || exit 1
  git pull-sub
  git submodule update --recursive --remote

  # JavaScript packages
  sudo yarn global upgrade

  # Python packages
  pip3 list --outdated --format=freeze | \
    grep -v '^\-e' | \
    cut -d = -f 1 | \
    xargs -n1 pip3 install -U --user


  # Vim
  vim +PlugUpgrade +PlugUpdate +qall
  rm ~/.vim/autoload/plug.vim.old > /dev/null 2>&1

  # Tmux
  cd ~/.tmux/plugins/tmux-battery && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-copycat && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-prefix-highlight && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-yank && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-better-mouse-mode && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-cpu && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-resurrect && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-continuum && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-pain-control && git checkout master && git pull
  cd ~/.tmux/plugins/tmux-sensible && git checkout master && git pull

  # Zsh
  cd ~/.oh-my-zsh || exit 1
  git checkout master
  git pull
  source ~/.zshrc

  cd "$CURRENT_DIR" || exit 1
}
