#!/bin/bash

function linte() {
  MONGO_URL=mongodb://localhost:27017/linte_dev meteor --settings settings.json
}

function linte-itau() {
  MONGO_URL=mongodb://localhost:27017/linte_dev_itau meteor --settings settings.json
}
