#!/bin/bash

function installMeteor() {
  if [ ! -d "$HOME/.meteor" ]; then
    curl https://install.meteor.com/ | sh
  fi
}

function linte() {
  installMeteor

  MONGO_URL=mongodb://localhost:27017/linte_dev meteor --settings settings.json
}

function linte-itau() {
  installMeteor

  MONGO_URL=mongodb://localhost:27017/linte_dev_itau meteor --settings settings.json
}
