#!/bin/bash

function mongodb-start() {
  mkdir -p ~/Workspace/Databases/MongoDB

  docker run \
    --detach \
    --name mongodb \
    --restart unless-stopped \
    --env "MONGO_INITDB_ROOT_USERNAME=root" \
    --env "MONGO_INITDB_ROOT_PASSWORD=root" \
    -v "$HOME/Workspace/Databases/MongoDB:/data/db" \
    --publish 27017:27017 \
    mongo:4-xenial
}

function mongodb-stop() {
  docker stop mongodb
}

function mongodb-purge() {
  mongodb-stop
  docker rm mongodb

  sudo rm -rf ~/Workspace/Databases/MongoDB
}
