#!/bin/bash

function mysql-start() {
  mkdir -p ~/Workspace/Databases/MySQL

  docker run \
    --name mysql \
    --restart unless-stopped \
    --env "MYSQL_ROOT_PASSWORD=root" \
    -v "$HOME/Workspace/Databases/MySQL:/var/lib/mysql" \
    --publish 3306:3306 \
    -d mysql:5.7
}

function mysql-stop() {
  docker stop mysql
}

function mysql-purge() {
  mysql-stop
  docker rm mysql

  sudo rm -rf ~/Workspace/Databases/MySQL
}
