#!/bin/bash

# Opens the current directory, otherwise opens the given location
if [[ "$(uname)" == "Linux" ]]; then
  function open() {
    if [ $# -eq 0 ]; then
      xdg-open . > /dev/null 2>&1;
    else
      xdg-open "$@" > /dev/null 2>&1;
    fi;
  }
fi
