#!/bin/bash

function postgresql-start() {
  mkdir -p ~/Workspace/Databases/PostgreSQL

  docker run \
    --detach \
    --name postgresql \
    --restart unless-stopped \
    --env "POSTGRES_USER=root" \
    --env "POSTGRES_PASSWORD=root" \
    -v "$HOME/Workspace/Databases/PostgreSQL:/var/lib/postgresql/data" \
    --publish 5432:5432 \
    postgres:10-alpine
}

function postgresql-stop() {
  docker stop postgresql
}

function postgresql-purge() {
  postgresql-stop
  docker rm postgresql

  sudo rm -rf ~/Workspace/Databases/PostgreSQL
}
