#!/bin/bash

function syncMongo() {
  sudo docker stop linte_mongodb3.4
  sudo docker rm linte_mongodb3.4
  sudo rm -rf ~/Workspace/mongodb/linte/

  mkdir -p ~/Workspace/mongodb/linte/dump
  sudo docker run \
    -v $HOME/Workspace/mongodb/linte:/data/db \
    --restart unless-stopped \
    --name linte_mongodb3.4 \
    --publish 27017:27017 \
    -d mongo:3.4

  echo "Starting MongoDB..."
  sleep 60

  # Linte
  LATEST_DUMP=`aws s3 ls s3://linte-backup-hourly/db-prod/  | sort | tail -n 1 | awk '{print $4}'`;
  aws s3 cp s3://linte-backup-hourly/db-prod/$LATEST_DUMP ~/Workspace/mongodb/linte/dump/$LATEST_DUMP
  tar -xvzf ~/Workspace/mongodb/linte/dump/$LATEST_DUMP -C ~/Workspace/mongodb/linte/dump
  rm -rf ~/Workspace/mongodb/linte/dump/$LATEST_DUMP
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdconfig.metadata.json
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdconfig.bson
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdtimeevents.metadata.json
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdtimeevents.bson
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdtraces.metadata.json
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdtraces.bson
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/meteor_accounts_loginServiceConfiguration.metadata.json
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/meteor_accounts_loginServiceConfiguration.bson
  sudo docker exec -it linte_mongodb3.4 mongorestore --db linte_dev /data/db/dump/${LATEST_DUMP//.tgz}/linte_production
  sudo docker exec -it linte_mongodb3.4 mongo linte_dev -port 27017 --eval 'db.users.update({}, { $set: { "services.password.bcrypt": "$2a$10$wcbNWVx3Ai7dz6FITdF8UelDD4A4g6ckMd5nuUOa6rQFcloclN9ie" } }, { multi: true })'
  rm -rf ~/Workspace/mongodb/linte/dump/*

  # Itaú
  LATEST_DUMP=`aws s3 ls s3://sa-east-1-linte-backup/linte-backup-hourly/db-prod/  | sort | tail -n 1 | awk '{print $4}'`;
  aws s3 cp s3://sa-east-1-linte-backup/linte-backup-hourly/db-prod/$LATEST_DUMP ~/Workspace/mongodb/linte/dump/$LATEST_DUMP
  tar -xvzf ~/Workspace/mongodb/linte/dump/$LATEST_DUMP -C ~/Workspace/mongodb/linte/dump
  rm -rf ~/Workspace/mongodb/linte/dump/$LATEST_DUMP
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdconfig.metadata.json
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdconfig.bson
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdtimeevents.metadata.json
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdtimeevents.bson
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdtraces.metadata.json
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/__kdtraces.bson
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/meteor_accounts_loginServiceConfiguration.metadata.json
  rm -rf ~/Workspace/mongodb/linte/dump/${LATEST_DUMP//.tgz}/linte_production/meteor_accounts_loginServiceConfiguration.bson
  sudo docker exec -it linte_mongodb3.4 mongorestore --db linte_dev_itau /data/db/dump/${LATEST_DUMP//.tgz}/linte_production
  sudo docker exec -it linte_mongodb3.4 mongo linte_dev_itau -port 27017 --eval 'db.users.update({}, { $set: { "services.password.bcrypt": "$2a$10$wcbNWVx3Ai7dz6FITdF8UelDD4A4g6ckMd5nuUOa6rQFcloclN9ie" } }, { multi: true })'
  rm -rf ~/Workspace/mongodb/linte/dump/*

  rm -rf ~/Workspace/mongodb/linte/dump
}
