#!/bin/bash

################################################################################
# Basic aliases
################################################################################
alias bc="bc -l"
alias cd..="cd .."
alias la="ls -aF"
alias ld="ls -ld"
alias less="less -R"
alias ll="ls -la"
alias mkdir="mkdir -pv"
alias more="more -R"
alias mount="mount | column -t"
alias mutt="neomutt"
alias ping="ping -c 5"
alias wget="wget -c -N"

################################################################################
# General
################################################################################
# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

################################################################################
# System specific
################################################################################
case "$(uname)" in
  Linux)

  ;;
  Darwin)
    # Canonical hex dump; some systems have this symlinked
    command -v hd > /dev/null || alias hd="hexdump -C"

    # macOS has no `md5sum`, so use `md5` as a fallback
    command -v md5sum > /dev/null || alias md5sum="md5"

    # # macOS has no `sha1sum`, so use `shasum` as a fallback
    command -v sha1sum > /dev/null || alias sha1sum="shasum"

		# Recursively delete `.DS_Store` files
		alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

		# Empty the Trash on all mounted volumes and the main HDD.
		# Also, clear Apple’s System Logs to improve shell startup speed.
		# Finally, clear download history from quarantine. https://mths.be/bum
		alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

		# Merge PDF files
		# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
		alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

    # Google Browsers
    alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
    alias canary='/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary'

    # Show/hide hidden files in Finder
    alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
    alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
  ;;
esac
