#!/usr/bin/env bash

# Always use color output for `ls`
alias ls="command ls --color"

# List all files colorized in long format, excluding . and ..
alias la="ls -lAF --color"

# List only directories
alias ld="ls -lF --color | grep --color=never \"^d\""

# Always enable colored `grep` output
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias zgrep="zgrep --color=auto"

# Always create parent folders if needed
alias mkdir="mkdir --parents --verbose"

# Stop after sending 5 packets
alias ping="ping -c 5"

# Recursively delete clean up folders
alias cleanup-node="find . -type d -name \"node_modules\" -exec rm -rf \"{}\" +"
alias cleanup-git="find . -type d -name \".git\" -exec rm -rf \"{}\" +"

# Print each PATH entry on a separate line
alias path="echo -e ${PATH//:/\\n}"

# Shred file
alias shred="shred -zvu -n 10"

# Use neomutt when available
if [ -x "$(command -v neomutt)" ]; then
  alias mutt="neomutt"
fi

# Use docker-compose as container when binary isn't available
if ! [ -x "$(command -v docker-compose)" ]; then
  alias docker-compose="docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v \"$PWD:/rootfs/$PWD\" -w=\"/rootfs/$PWD\" docker/compose:1.24.0"
fi

# Lock the screen (when going AFK)
alias afk="gnome-screensaver-command --lock"
