#!/usr/bin/env bash

case "$(uname)" in
  Linux)

  ;;
  Darwin)

  ;;
esac

# Fzf
if [ -f ~/.fzf.zsh ] || [ -h ~/.fzf.zsh ]; then
  source ~/.fzf.zsh

  # Faster file searching
  export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
fi
