#!/usr/bin/env bash

case "$(uname)" in
  Linux)

  ;;
  Darwin)
    # coreutils
    export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"

    # findutils
    export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"

    # curl
    export PATH="/usr/local/opt/curl/bin:$PATH"

    # openssl
    export PATH="/usr/local/opt/openssl/bin:$PATH"
  ;;
esac
