#!/usr/bin/env bash

################################################################################
# System specific settings
################################################################################
case "$(uname)" in
  Linux)

  ;;
  Darwin)

  ;;
esac

################################################################################
# Shell
################################################################################
# Vi mode
set -o vi

# Ignore duplicated entries
export HISTCONTROL=ignoredups

# Ignore some commands
export HISTIGNORE="cd:ls:[bf]g:clear:exit"

# Set language
export LANG=pt_BR.UTF-8

################################################################################
# Oh-my-zsh
################################################################################
export ZSH=~/.oh-my-zsh
ZSH_THEME="awesomepanda"
DISABLE_AUTO_UPDATE="true"
HIST_STAMPS="dd/mm/yyyy"
plugins=(
  docker
  docker-compose
  docker-machine
  dotenv
  gem
  git
  github
  gpg-agent
  gulp
  helm
  heroku
  iterm2
  keychain
  kubectl
  minikube
  node
  npm
  npx
  osx
  pip
  pipenv
  postgres
  python
  redis-cli
  ripgrep
  rsync
  ssh-agent
  sublime
  sudo
  terraform
  tmux
  ubuntu
  vagrant
  vi-mode
  vscode
  xcode
  yarn
)
