#!/usr/bin/env bash

################################################################################
# Shell
################################################################################
# Vi mode
set -o vi

# Ignore duplicated entries
export HISTCONTROL=ignoredups

# Ignore some commands
export HISTIGNORE="cd:ls:[bf]g:clear:exit"

# Set language
export LANG=pt_BR.UTF-8

################################################################################
# Oh-my-zsh
################################################################################
export ZSH=~/.oh-my-zsh
ZSH_THEME="awesomepanda"
DISABLE_AUTO_UPDATE="true"
HIST_STAMPS="dd/mm/yyyy"
plugins=(gpg-agent ssh-agent tmux vi-mode)
